Areas/Account/Controllers/UrlsController.cs
using AireGo.Areas.Account.Models;
using AireGo.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AireGo.Areas.Account.Controllers
{
    public class UrlsController : BaseController
    {
        private IFreeSql _sql;
        public UrlsController(IFreeSql sql) => _sql = sql;
        public IActionResult Index() => View();
        public IActionResult Add() => View();
        public async Task<IActionResult> Edit(int? id)
        {
            var ids = id ?? -1;
            if (ids <= 0) return RedirectToAction("Index");

            var res = await _sql.Select<UrlsMap>().Where(e => e.Id == id).FirstAsync();
            if (res == null)
                return Index();
            else
                ViewData["url_id"] = res.Id;

            return View();
        }
        public async Task<RespMap> Get(int page, int size)
        {
            var resp = new RespMap();

            try
            {
                var list = await _sql.Select<UrlsMap>()
                    .Skip((page - 1) * size).Take(size)
                    .ToListAsync();

                resp.Code = 200;
                resp.Message = "处理成功";
                resp.Data = list;
            }
            catch (Exception ex)
            {
                resp.Code = 500;
                resp.Message = ex.Message;
                resp.Data = ex;
            }

            return resp;
        }
        public async Task<RespMap> GetMap(int? id)
        {
            var ids = id ?? -1;
            var resp = new RespMap();

            try
            {
                var res = await _sql.Select<UrlsMap>().Where(e => e.Id == id).FirstAsync();
                resp.Code = 200;
                resp.Message = "获取成功";
                resp.Data = res;
            }
            catch (Exception ex)
            {
                resp.Code = 500;
                resp.Message = ex.Message;
                resp.Data = ex;
            }
            return resp;
        }
        public async Task<RespMap> Push(int id, string title, string tag, string url,string posttime, string desc, string action = "add")
        {
            var resp = new RespMap();
            try
            {
                var res = 0;

                if (action.Equals("add"))
                {
                    var model = new UrlsMap()
                    {
                        Title = title,
                        Posttime = DateTime.Now.ToString("yyyy/MM/dd"),
                        Tag = tag,
                        Url = url,
                        Description = desc
                    };
                    res = await _sql
                        .Insert(model)
                        .ExecuteAffrowsAsync();

                    if (res > 0)
                    {
                        resp.Code = 200;
                        resp.Message = "添加成功";
                        resp.Data = res;
                    }
                    else
                    {
                        resp.Code = 200;
                        resp.Message = "添加失败";
                        resp.Data = res;
                    }
                }
                else if(action.Equals("edit"))
                {
                    var model = new UrlsMap()
                    {
                        Title = title,
                        Posttime = posttime,
                        Tag = tag,
                        Url = url,
                        Description = desc
                    };

                    res = await _sql
                        .Update<UrlsMap>()
                        .Where(e => e.Id == id)
                        .Set(e => e.Title, model.Title)
                        .Set(e => e.Url, model.Url)
                        .Set(e => e.Description, model.Description)
                        .ExecuteAffrowsAsync();

                    if (res > 0)
                    {
                        resp.Code = 200;
                        resp.Message = "更新成功";
                        resp.Data = res;
                    }
                    else
                    {
                        resp.Code = 200;
                        resp.Message = "更新失败";
                        resp.Data = res;
                    }
                }
            }
            catch (Exception ex)
            {
                resp.Code = 500;
                resp.Message = ex.Message;
                resp.Data = ex;
            }
            return resp;
        }
    }
}

Areas/Account/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1">
    <link rel="stylesheet" type="text/css" href="//oss.boselor.com/res/tpl/clearmin/assets/css/bootstrap-clearmin.min.css">
    <link rel="stylesheet" type="text/css" href="//oss.boselor.com/res/tpl/clearmin/assets/css/roboto.css">
    <link rel="stylesheet" type="text/css" href="//oss.boselor.com/res/tpl/clearmin/assets/css/material-design.css">
    <link rel="stylesheet" type="text/css" href="//oss.boselor.com/res/tpl/clearmin/assets/css/small-n-flat.css">
    <link rel="stylesheet" type="text/css" href="//oss.boselor.com/res/tpl/clearmin/assets/css/font-awesome.min.css">
    <title>@ViewData["Title"] - AireGo</title>
</head>
<body class="cm-no-transition cm-1-navbar">
    <div id="cm-menu">
        <nav class="cm-navbar cm-navbar-primary">
            <div class="cm-flex"><a asp-area="Account" asp-controller="Home" asp-action="Index" class="cm-logo"></a></div>
            <div class="btn btn-primary md-menu-white" data-toggle="cm-menu"></div>
        </nav>
        <div id="cm-menu-content">
            <div id="cm-menu-items-wrapper">
                <div id="cm-menu-scroller">
                    <ul class="cm-menu-items">
                        <li class="active"><a asp-area="Account" asp-controller="Home" asp-action="Index" class="sf-dashboard">控制面板</a></li>
                        <li class="cm-submenu">
                            <a class="sf-map-map-marker">管理连接<span class="caret"></span></a>
                            <ul>
                                <li><a asp-area="Account" asp-controller="Urls" asp-action="Add">添加列表</a></li>
                                <li><a asp-area="Account" asp-controller="Urls" asp-action="Index">管理连接</a></li>
                            </ul>
                        </li>
                        <li class="cm-submenu">
                            <a class="sf-cogs">管理数据<span class="caret"></span></a>
                            <ul>
                                <li><a class="sf-database" asp-area="Account" asp-controller="Settings" asp-action="Backup">备份数据</a></li>
                                <li><a class="sf-profile" asp-area="Account" asp-controller="Settings" asp-action="Profile">用户设置</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <header id="cm-header">
        <nav class="cm-navbar cm-navbar-primary">
            <div class="btn btn-primary md-menu-white hidden-md hidden-lg" data-toggle="cm-menu"></div>
            <div class="cm-flex">
                <h1>@ViewData["Title"]</h1>
                <form id="cm-search" action="index.html" method="get">
                    <input type="search" name="q" autocomplete="off" placeholder="Search...">
                </form>
            </div>
            @*<div class="pull-right">
                <div id="cm-search-btn" class="btn btn-primary md-search-white" data-toggle="cm-search"></div>
            </div>
            <div class="dropdown pull-right">
                <button class="btn btn-primary md-notifications-white" data-toggle="dropdown"> <span class="label label-danger">23</span> </button>
                <div class="popover cm-popover bottom">
                    <div class="arrow"></div>
                    <div class="popover-content">
                        <div class="list-group">
                            <a href="#" class="list-group-item">
                                <h4 class="list-group-item-heading text-overflow">
                                    <i class="fa fa-fw fa-envelope"></i> Nunc volutpat aliquet magna.
                                </h4>
                                <p class="list-group-item-text text-overflow">Pellentesque tincidunt mollis scelerisque. Praesent vel blandit quam.</p>
                            </a>
                            <a href="#" class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <i class="fa fa-fw fa-envelope"></i> Aliquam orci lectus
                                </h4>
                                <p class="list-group-item-text">Donec quis arcu non risus sagittis</p>
                            </a>
                            <a href="#" class="list-group-item">
                                <h4 class="list-group-item-heading">
                                    <i class="fa fa-fw fa-warning"></i> Holy guacamole !
                                </h4>
                                <p class="list-group-item-text">Best check yo self, you're not looking too good.</p>
                            </a>
                        </div>
                        <div style="padding:10px"><a class="btn btn-success btn-block" href="#">Show me more...</a></div>
                    </div>
                </div>
            </div>*@
            @*<div class="dropdown pull-right">
                <button class="btn btn-primary md-account-circle-white" data-toggle="dropdown"></button>
                <ul class="dropdown-menu">
                    <li class="disabled text-center">
                        <a style="cursor:default;"><strong>John Smith</strong></a>
                    </li>
                    <li class="divider"></li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                    </li>
                    <li>
                        <a href="#"><i class="fa fa-fw fa-cog"></i> Settings</a>
                    </li>
                    <li>
                        <a href="login.html"><i class="fa fa-fw fa-sign-out"></i> Sign out</a>
                    </li>
                </ul>
            </div>*@
        </nav>
    </header>
    <div id="global">
        @*<div class="container-fluid cm-container-white">
            <h2 style="margin-top:0;">Welcome to Clearmin template demo !</h2>
            <p>Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Vestibulum tortor quam, feugiat vitae, ultricies eget, tempor sit amet, ante. Donec eu libero sit amet quam egestas semper. Aenean ultricies mi vitae est. Mauris placerat eleifend leo. Quisque sit amet est et sapien ullamcorper pharetra. Vestibulum erat wisi, condimentum sed, commodo vitae, ornare sit amet, wisi. Aenean fermentum, elit eget tincidunt condimentum, eros ipsum rutrum orci, sagittis tempus lacus enim ac dui. Donec non enim in turpis pulvinar facilisis. Ut felis.</p>
        </div>*@
        <div class="container-fluid" style="margin-top:1rem;">
            @RenderBody()
        </div>
        <footer class="cm-footer"><span class="pull-left">AireGo</span><span class="pull-right">&copy; @DateTime.Now.Year</span></footer>
    </div>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/lib/jquery.min.js"></script>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/jquery.mousewheel.min.js"></script>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/jquery.cookie.min.js"></script>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/fastclick.min.js"></script>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/bootstrap.min.js"></script>
    <script src="//oss.boselor.com/res/tpl/clearmin/assets/js/clearmin.min.js"></script>
    @RenderSection("Scripts", false)
</body>
</html>